name: "Thank you"
description: "Replying to participants"
runs:
  using: "node16"
  main: "index.js"
steps:
  - name: Checkout code
    uses: actions/checkout@v3
  - name: Use Node.js
    uses: actions/setup-node@v3
    with:
      node-version: 16

  - name: Cache node modules
    id: npm-cache
    uses: actions/cache@v3
    with:
      path: node_modules
      key: npm-packages-${{ hashFiles('**/package-lock.json') }}

  - name: Install Dependencies
    if: steps.cache.outputs.cache-hit != 'true'
    run: npm install

inputs:
  token: description
  required: true
