name: Cache Test

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - with:
          fetch-deps: 1

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: Check changed paths
        id: check-paths
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo $file
            if [[ $file =~ .*\.(js$|ts$) ]]; then
               echo "The extension of '$file' matches .js|.json";
            fi
            if [[ $file == app/docs/* ]]; then
              echo "DOCS_CHANGED=true" >> $GITHUB_ENV
            fi
            if [[ $file == packages/ui/* ]]; then
              echo "UI_CHANGED=true" >> $GITHUB_ENV
            fi
          done
