name: Check PR Labels on Push

on:
  push:
    branches:
      - main  # 필요한 브랜치로 수정

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get PR labels
        id: pr-labels
        run: |
          PR_NUMBER=$(curl -s https://api.github.com/repos/${{ github.repository }}/pulls?state=open | jq -r '.[] | select(.head.ref=="${GITHUB_REF##*/}") | .number')
          if [ -z "$PR_NUMBER" ]; then
            echo "No open PR found for this push"
            exit 1
          fi

          LABELS=$(curl -s https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/labels)
          echo "Labels: $LABELS"
          echo "::set-output name=labels::$LABELS"
          
      - name: Process PR Labels
        run: |
          if [[ "${{ steps.pr-labels.outputs.labels }}" == *"docs"* ]]; then
            echo "Label is present!"
            # 원하는 작업 수행
          else
            echo "Label not found"
          fi
