name: Print Branch Name

on:
  push:
    branches:
      - main

jobs:
  print-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Print source branch name
        run: |
          echo "Push came from branch $(git rev-parse --abbrev-ref HEAD@{1})"
